const TodoActionTypes = {
  TOGGLE_TODO: "TOGGLE_TODO",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  SAVE_EDIT_TODO: "SAVE_EDIT_TODO",
  CANCEL_EDIT_TODO: "CANCEL_EDIT_TODO",
  UPDATE_QUANTITY_TODO: "UPDATE_QUANTITY_TODO",
  TODO_REFRESH_REQUEST: "TODO_REFRESH_REQUEST",
  TODO_REFRESH_DONE: "TODO_REFRESH_DONE",
  TODO_INSERT_REQUEST: "TODO_INSERT_REQUEST",
  TODO_EDIT_REQUEST: "TODO_EDIT_REQUEST",
  TODO_DELETE_REQUEST: "TODO_DELETE_REQUEST",
  TODO_UPDATE_QUANTITY_REQUEST: "TODO_UPDATE_QUANTITY_REQUEST",
  TODO_TOGGLE_REQUEST: "TODO_TOGGLE_REQUEST"
};

export default TodoActionTypes;
