const TodoActionTypes = {
  ADD_TODO: "ADD_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  SAVE_EDIT_TODO: "SAVE_EDIT_TODO",
  CANCEL_EDIT_TODO: "CANCEL_EDIT_TODO",
  UPDATE_QUANTITY_TODO: "UPDATE_QUANTITY_TODO",
  TODO_REFRESH_REQUEST: "TODO_REFRESH_REQUEST",
  TODO_REFRESH_DONE: "TODO_REFRESH_DONE"
};

export default TodoActionTypes;
